### ISSUE TITLE
Ingen dubbelcheck på anginen pizzeria_id vid skapande av en meny till en pizzeria

### ISSUE THREAD

**Issue by johnnypesola** [mp222sf/1dv450-mp222sf#10]
Skickar man följande värde (POST) till `api/v1/menus` så skapas objektet utan problem. En check för att en pizzeria med det angivna id:t existerar vore bra för att slippa framtida problem.

```
{
    "menu": {
            "name": "testarmendsad",
            "pizzeria_id": 12121
        }
}
```

**Comment by mp222sf** [comment]
Löst.
