### ISSUE TITLE
Ingen felhantering vid ofullständig PUT data

### ISSUE THREAD

**Issue by johnnypesola** [mp222sf/1dv450-mp222sf#12]
Vid en PUT till `api/v1/creator/1` så möts man av ett `ActionController::ParameterMissing` fel. Nedan är exempeldatat jag skickade.

```
{
    "creator": {

        }
}
```

Samma förbättring på felhantering kan göras vid alla PUT anrop. Detta är ingenting kritiskt, men ser snyggt ut för användarna av API:t.

**Comment by mp222sf** [comment]
Löst.
Fixat detta till alla CREATE, PUT och DELETE-anrop.
Ger nu ett felmeddelande som säger att parametrar saknas.
