### ISSUE TITLE
API nyckel krävs inte vid varje anrop

### ISSUE THREAD

**Issue by johnnypesola** [mp222sf/1dv450-mp222sf#13]
API:et ser i helheten ut att fungera bra. Implementering av autentisering finns för POST, PUT och DELETE till resurser, men kontroll av API-nyckel saknas. En check av API nyckeln behövs också vid dessa anrop.
Följande rad är hämtad från [uppgiftsbeskrivningen](https://coursepress.lnu.se/kurs/webbramverk/webb-api-back-end/) 

> Varje anrop ska kräva en giltig API-nyckel skapad i applikationen gjord i första delen

**Comment by mp222sf** [comment]
Löst.
Nu krävs en giltlig API-nyckel vid varje POST, PUT och DELETE-anrop.
