### ISSUE TITLE
Ingen felhantering för strängvärden för Limit parametern

### ISSUE THREAD

**Issue by johnnypesola** [mp222sf/1dv450-mp222sf#8]
Anger man `api/v1/menus?&limit=fisk&offset=1` så möts man av ohanterad argument error. Det här verkar vara lika på alla api anrop där limit parametern används.

**Comment by mp222sf** [comment]
Löst.
Matar man in fel värde i både Limit och Offset hämtas alla objekt.
Matar man in fel värde Limit men rätt i Offset så används Offset. Och tvärtom.
Inget felmeddelande kommer att ges vid inmatning av fel värde.
